import 'dart:math';

String getRandomContext() {
  var rng = Random();
  return contexts[rng.nextInt(contexts.length)];
}

List<String> contexts = [
  "family dinner",
  "morning routine",
  "holiday shopping",
  "mountain hiking",
  "city exploration",
  "evening walk",
  "beach vacation",
  "school days",
  "road trip",
  "cooking dinner",
  "grocery shopping",
  "music festival",
  "home renovation",
  "garden work",
  "coffee",
  "office meeting",
  "train journey",
  "winter sports",
  "summer camping",
  "birthday party",
  "book club",
  "university lecture",
  "wedding preparation",
  "children's playground",
  "farm visit",
  "forest adventure",
  "desert safari",
  "space exploration",
  "art exhibition",
  "football match",
  "romantic dinner",
  "doctor's appointment",
  "movie night",
  "weekend getaway",
  "yoga session",
  "fitness training",
  "baking cookies",
  "wine tasting",
  "autumn picnic",
  "spring cleaning",
  "library study",
  "museum visit",
  "park picnic",
  "zoo trip",
  "concert night",
  "theater performance",
  "restaurant review",
  "beauty salon",
  "car maintenance",
  "television show",
  "pet care",
  "campfire storytelling",
  "roller coaster",
  "magic show",
  "ballet class",
  "opera evening",
  "jazz club",
  "fishing trip",
  "sailing adventure",
  "beach volleyball",
  "skydiving experience",
  "scuba diving",
  "mountain biking",
  "rock climbing",
  "horseback riding",
  "pottery class",
  "painting lesson",
  "photography session",
  "fashion show",
  "charity event",
  "political debate",
  "science fair",
  "history tour",
  "architecture walk",
  "flower arranging",
  "bird watching",
  "comedy club",
  "poetry reading",
  "writing workshop"
];