db:
  user: "root"
  pass: "root"
  name: "maindb"
  host: "localhost"
  port: "3306"
  migration:
    dir: "./migrations"
    run: true


auth:
  github:
    authurl: "https://github.com/login/oauth/authorize"
    clientid: "ecd716b79e399c2d4ae0"
    clientsecret: "bd86f846f5cfe648bbce4768cff3ab95256464c5"
    tokenurl: "https://github.com/login/oauth/access_token"
    apibaseurl: "https://api.github.com"
    redirecturl: "http://localhost:8081/github/callback"

server:
  port: ":8081"
